Repository ISPP-2425-G4/borroo, pull requests merged in 2025-04, with the labels that each got.

#384 Backend perfil de empresa
  backend/usuarios/models.py
  backend/usuarios/serializers.py
  backend/usuarios/views.py
Labels: Subgrupo 1, Backend

#379 Full stack inicio de sesion
  backend/usuarios/views.py
  frontend/src/Login.jsx
Labels: Subgrupo 2, Fullstack

#378 Añadir el logo en el navbar y quitar el boton del carrito
  frontend/src/Navbar.jsx
Labels: Subgrupo 2, Frontend

#391 Feature/backend editar perfil
  backend/seeders.py
  backend/usuarios/models.py
  backend/usuarios/serializers.py
  backend/usuarios/urls.py
  backend/usuarios/views.py
Labels: Subgrupo 1, Backend

#396 Frontend de editar un perfil
  backend/seeders.py
  backend/usuarios/serializers.py
  frontend/src/AdminDashboard.jsx
  frontend/src/Profile.jsx
Labels: Subgrupo 1, Frontend

#392 Workflow changelog
  .github/workflows/release-with-changelog.yml
  .releaserc.json
Labels: Subgrupo 1, Backend

#404 Las valoraciones de los usuarios visualmente en el catalogo
  backend/objetos/serializers.py
  frontend/src/Layout.jsx
Labels: Subgrupo 2

#408 Frontend de editar un perfil
  backend/rentas/views.py
  frontend/src/Profile.jsx
Labels: Subgrupo 1, Backend, Frontend

#411 fix: arreglo visual del formulario de update item
  frontend/src/UpdateItem.jsx
Labels: Subgrupo 1, Frontend

#401 Frontend de perfil de empresa
  frontend/src/SignUp.jsx
Labels: Subgrupo 2, Frontend

#390 Feature/backend logica negocio
  backend/rentas/views.py
  frontend/src/RentRequestBoard.jsx
  frontend/src/ShowItem.jsx
Labels: Subgrupo 2, Fullstack

#415 Feature/fullstack reporte de usuarios
  backend/usuarios/models.py
  backend/usuarios/serializers.py
  backend/usuarios/urls.py
  backend/usuarios/views.py
  frontend/src/Profile.jsx
  frontend/src/ShowItem.jsx
Labels: Subgrupo 1, Fullstack

#413 Frontend añadir las politicas de privacidad etc en el footer y en el registro
  frontend/docs_frontend/Licencias.md
  frontend/docs_frontend/Politica-de-privacidad.md
  frontend/docs_frontend/SLA.md
  frontend/docs_frontend/Terminos-servicio.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/styles/Footer.css
  frontend/src/App.jsx
  frontend/src/SignUp.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/MarkdownViewer.jsx
  frontend/src/documents/Licenses.jsx
  frontend/src/documents/PrivacyPolicy.jsx
  frontend/src/documents/Sla.jsx
  frontend/src/documents/TermsAndConditions.jsx
Labels: Subgrupo 2, Frontend

#414 Feature/frontend informacion sobre que he alquilado
  frontend/src/components/RequestCardsContainer.jsx
Labels: Subgrupo 2, Frontend

#429 Feature/fullstack admin obtener reportes
  backend/seeders.py
  backend/usuarios/views.py
  frontend/src/AdminItemDashboard.jsx
  frontend/src/AdminReportsDashboard.jsx
  frontend/src/App.jsx
  frontend/src/Navbar.jsx
  frontend/src/ShowItem.jsx
Labels: Subgrupo 1, Fullstack

#432 Pruebas para la funcionalidad de pago(Unitarias)
  backend/pagos/urls.py
  backend/tests/unit/test_payments.py
  backend/usuarios/models.py
Labels: Subgrupo 1, Fullstack

#430 Creación de pruebas unitarias y test faltantes subgrupo1
  backend/objetos/models.py
  backend/objetos/views.py
  backend/tests/unit/test_crud_ask_for_a_rent.py
  backend/tests/unit/test_search_items.py
Labels: Subgrupo 1, Fullstack

#448 Bug rechazar posibilidad de cambiar de plan premium a gratis directamente
  backend/pagos/views.py
  backend/seeders.py
  backend/usuarios/models.py
  backend/usuarios/serializers.py
  backend/usuarios/views.py
  frontend/src/SubscriptionScreen.jsx
Labels: Subgrupo 3, Fullstack

#445 Frontend chat y mensajeria
  backend/chats/serializers.py
  frontend/src/App.jsx
  frontend/src/Messages.jsx
  frontend/src/Navbar.jsx
  frontend/src/Profile.jsx
  frontend/src/components/RequestCardsContainer.jsx
  frontend/src/components/SendMessageButton.jsx
Labels: Subgrupo 2, Frontend

#440 Feature/posibilidad cancelar pedidos aceptados y o pagados
  backend/rentas/views.py
  frontend/public/styles/Modal.css
  frontend/src/components/RequestCardsContainer.jsx
Labels: Subgrupo 2

#443 feat: Valoracion usuario en descripcion del objeto en alquiler
  frontend/package-lock.json
  frontend/package.json
  frontend/src/ShowItem.jsx
  frontend/src/components/StarRating.jsx
Labels: Subgrupo 2, Frontend

#461 Fix: Errores en productos destacados
  backend/objetos/views.py
  backend/usuarios/views.py
  frontend/src/ShowItem.jsx
Labels: Subgrupo 1, Fullstack

#464 Feature/fullstack generar incidencia si algo no ha ido bien en un alquiler
  backend/borroo/settings.py
  backend/borroo/urls.py
  backend/rentas/serializers.py
  backend/tickets/__init__.py
  backend/tickets/admin.py
  backend/tickets/apps.py
  backend/tickets/migrations/__init__.py
  backend/tickets/models.py
  backend/tickets/serializers.py
  backend/tickets/tests.py
  backend/tickets/urls.py
  backend/tickets/views.py
  frontend/src/AdminItemDashboard.jsx
  frontend/src/App.jsx
  frontend/src/CreateItem.jsx
  frontend/src/ListTickets.jsx
  frontend/src/Navbar.jsx
  frontend/src/NewTicketForm.jsx
  frontend/src/Profile.jsx
  frontend/src/components/FormStyles.jsx
  frontend/src/components/ImagePreview.jsx
  frontend/src/components/RequestCardsContainer.jsx
Labels: Subgrupo 2, Fullstack

#477 Creación de pruebas unitarias y test faltantes subgrupo1
  backend/pytest.ini
  backend/tests/e2e/test_search_items/test_filter_by_cancellation_type.py
  backend/tests/e2e/test_search_items/test_filter_by_category.py
  backend/tests/e2e/test_search_items/test_filter_by_type_of_price.py
  backend/tests/e2e/test_search_items/test_search_by_title.py
  backend/tests/unit/test_payments.py
  backend/tests/unit/test_search_items.py
  frontend/src/Layout.jsx
Labels: Subgrupo 1, Fullstack

#480 fix: arreglar eliminar boton cancelar si el alquiler ya ha pasado
  frontend/src/components/RequestCardsContainer.jsx
Labels: Subgrupo 2

#481 Documentation/docu pilots
  docs/Sprint 3/Pilots CA/firmasUp/firma_angel.png
  docs/Sprint 3/Pilots CA/firmasUp/firma_daniel.png
  docs/Sprint 3/Pilots CA/firmasUp/firma_josue.png
  docs/Sprint 3/Pilots CA/firmasUp/firma_karim.png
  docs/Sprint 3/Pilots CA/firmasUp/firma_pablo.png
  docs/Sprint 3/Pilots CA/pilotUsersCommitmentAgreement.md
  docs/Sprint 3/Pilots CA/pilotUsersCommitmentAgreementAngel.md
  docs/Sprint 3/Pilots CA/pilotUsersCommitmentAgreementDanielFlores.md
  docs/Sprint 3/Pilots CA/pilotUsersCommitmentAgreementExternos.md
  docs/Sprint 3/Pilots CA/pilotUsersCommitmentAgreementJosuéRodríguez.md
  docs/Sprint 3/Pilots CA/pilotUsersCommitmentAgreementKarim.md
  docs/Sprint 3/Pilots CA/pilotUsersCommitmentAgreementPabloOlivencia.md
  docs/Sprint 3/Resumen Feedback.md
  docs/Sprint 3/pilotUsers.md
  docs/Sprint 3/pilotUsersPerformanceEvaluation.md
  docs/Sprint 3/pilots(encuesta).md
Labels: Subgrupo 2

#485 Arreglo DNI y cuenta empresa
  backend/usuarios/models.py
  frontend/src/Profile.jsx
Labels: Subgrupo 2

#518 Feature/fullstack pagar subscripción mediante saldo
  backend/pagos/urls.py
  backend/pagos/views.py
  frontend/src/SubscriptionScreen.jsx
Labels: Subgrupo 1, Fullstack

#519 BUG: Cambiar texto en anuncios
  frontend/src/ListItemRequests.jsx
Labels: Subgrupo 2, Frontend

#520 Feature/frontend simulación de retirada de saldo
  backend/pagos/urls.py
  backend/pagos/views.py
  frontend/src/Navbar.jsx
  frontend/src/Profile.jsx
Labels: Subgrupo 1, Fullstack
